### ISSUE TITLE
cut+paste error in blog

### ISSUE THREAD

**Issue by ecki** [GregSutcliffe/puppet-ssh_statickeys#3]
Sorry to use Github, but in the blog the .pub file sample snippet uses `content => "ssh-rsa $rsa_priv ...` I guess that should be `$rsa_pub`? Thanks for the module.

**Comment by GregSutcliffe** [comment]
Sorry for the long long wait, but I finally fixed this, thanks :)

**Comment by ecki** [comment]
Thanks for fixing it (currently the "my blog" link in the README.md points to a 404).

**Comment by GregSutcliffe** [comment]
@ecki thanks, I saw that too. Looks like DNS weirdness, seems OK now
