### ISSUE TITLE
Filemode

### ISSUE THREAD

**Issue by Nikonuk21** [GregSutcliffe/puppet-ssh_statickeys#5]
Error: Failed to apply catalog: Parameter mode failed on File[/etc/ssh/ssh_host_rsa_key]: The file mode specification must be a string, not 'Fixnum'

This is being used on the newest Puppet Server / Puppet Agent.

Also had to change directoty in ssh_keygen.rb to /etc/puppetlabs. 

The user also as to be set to puppet:puppet on the Puppet master directory

chown -R puppet:puppet /etc/puppetlabs/ssh

Raised issue just for awareness.

**Comment by GregSutcliffe** [comment]
Thanks, I'll see if I can replicate.

**Comment by GregSutcliffe** [comment]
Should be fixed in #4 - please re-open if you still see this :)
